### ISSUE TITLE
Login / Register not working as expected

### ISSUE THREAD

**Issue by 3dmedium** [ebu/pi-list#113]
I deployed the latest Dockjer Container (Ubuntu 20.04) and tried to login.

Open webinterface (Port 8080) (Firefox, but tried Chrome and Opera too)
After clicking Register a empty page opens.
In the Browser Debugger there are lots of errors. (CORS errors)
They lead me to accessing the page via Port 80 / Reconfigure docekr container.
![image](https://user-images.githubusercontent.com/18495706/103488012-cd3e0c80-4e09-11eb-8fa8-b24d55ddb715.png)

After that there are still errors with react.
Login and register are not working for me is there anything I missed or can someone reproduce these errors

![image](https://user-images.githubusercontent.com/18495706/103488061-1beba680-4e0a-11eb-9977-70dee0edd5a4.png)

![image](https://user-images.githubusercontent.com/18495706/103488066-2312b480-4e0a-11eb-96fd-0d14db32cc36.png)

**Comment by pedro-alves-ferreira** [comment]
Hello,

I'm sorry to know that you are having problems running LIST.

Can you please make sure that you are using the up to date 
docker-compose.yml file here:

|https://raw.githubusercontent.com/ebu/pi-list/master/docs/docker-compose.yml|

as mentioned here: 
https://github.com/ebu/pi-list/blob/master/docs/how-to-install-on-local-docker.md

Make sure you access it using http://localhost port 80.

Please let us know if that does not solve the problem.

Regards,

Pedro

**Comment by tagYourPregnant** [comment]
I also am having this issue. Register and login both take me to a blank page. Anything I can do to fix? I have verified that I am using the latest docker-compose.yml file.

Also the online version LIST looks like it has the exact same problem. 

https://list.ebu.io/login

Any assistance would be appreciated. Thanks

**Comment by pedro-alves-ferreira** [comment]
Hello,

I have just tried it on list.ebu.io and it worked correctly for me.
Could this be a compatibility issue with the browser? Which browser are you using?

Also, when running it locally, make sure you do a docker-compose pull on the directory where the docker-compose.yml is, before the docker-compose up. This will ensure that the latest version is downloaded.
________________________________
De: tagYourPregnant <notifications@github.com>
Enviado: 15 de janeiro de 2021 18:42
Para: ebu/pi-list <pi-list@noreply.github.com>
Cc: Pedro Ferreira <pedro@bisect.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [ebu/pi-list] Login / Register not working as expected (#113)


I also am having this issue. Register and login both take me to a blank page. Anything I can do to fix? I have verified that I am using the latest docker-compose.yml file.

Also the online version LIST looks like it has the exact same problem.

https://list.ebu.io/login

Any assistance would be appreciated. Thanks

**Comment by tagYourPregnant** [comment]
Thanks for the response. 

I have tried it on edge, chrome, and firefox. All of them take me to a blank screen. I have also tried two different computers.

**Comment by pedro-alves-ferreira** [comment]
I have just tried it on Chrome and Firefox on a Ubuntu system and both worked correctly.
The only thing I can think of is something on local storage (which would be odd for those many browsers). Can you please open the browser settings and clear the local storage for list.ebu.io?
________________________________
De: tagYourPregnant <notifications@github.com>
Enviado: 15 de janeiro de 2021 18:54
Para: ebu/pi-list <pi-list@noreply.github.com>
Cc: Pedro Ferreira <pedro@bisect.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [ebu/pi-list] Login / Register not working as expected (#113)


Thanks for the response.

I have tried it on edge, chrome, and firefox. All of them take me to a blank screen. I have also tried two different computers.

**Comment by tagYourPregnant** [comment]
I have cleared the storage and it still does not work. I have asked colleagues on other networks to try and they have the same issue. My cell phone goes to a blank screen also. Do you have another network environment to test from? Different PC or cell phone, etc. 

Thanks for your assistance.

**Comment by pedro-alves-ferreira** [comment]
I am absolutely puzzled. I tried with PCs and smartphones and it always worked.
Could you please open the browser's javascript console, refresh the page and send me the output?


No dia 15/01/2021, às 19:12, tagYourPregnant <notifications@github.com> escreveu:

﻿

I have cleared the storage and it still does not work. I have asked colleagues on other networks to try and they have the same issue. My cell phone goes to a blank screen also. Do you have another network environment to test from? Different PC or cell phone, etc.

Thanks for your assistance.

**Comment by tagYourPregnant** [comment]
Just to be clear, you are clicking register and it takes you to a page to register? When I click register it goes blank, here is the console output after I go to the page that is blank.

Download the React DevTools for a better development experience: https://fb.me/react-devtools
api.js:7 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
(anonymous) @ api.js:7
api/meta/features:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
react-dom.development.js:88 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Unknown (created by component)
    in component (created by Context.Consumer)
u @ react-dom.development.js:88
api/user:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
api/meta/version:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
api/user/gdpr:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
api/news:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
user/register:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `children` supplied to `Er`.
    in Er (created by uT)
    in uT (created by o)
    in div (created by o)
    in div (created by o)
    in div (created by o)
    in o (created by Context.Consumer)
    in t
    in t
    in t (created by t)
    in t
n @ checkPropTypes.js:20
react-dom.development.js:13413 Uncaught Error: Objects are not valid as a React child (found: Error: Request failed with status code 500). If you meant to render a collection of children, use an array instead.
    in div (created by Er)
    in div (created by Er)
    in Er (created by uT)
    in uT (created by o)
    in div (created by o)
    in div (created by o)
    in div (created by o)
    in o (created by Context.Consumer)
    in t
    in t
    in t (created by t)
    in t
    at ku (react-dom.development.js:13413)
    at react-dom.development.js:14313
    at zd (react-dom.development.js:16762)
    at react-dom.development.js:17302
    at sp (react-dom.development.js:18627)
    at HTMLUnknownElement.g (react-dom.development.js:188)
    at Object.f (react-dom.development.js:237)
    at _ (react-dom.development.js:292)
    at im (react-dom.development.js:23203)
    at Bh (react-dom.development.js:22157)
react-dom.development.js:19527 The above error occurred in the <div> component:
    in div (created by Er)
    in div (created by Er)
    in Er (created by uT)
    in uT (created by o)
    in div (created by o)
    in div (created by o)
    in div (created by o)
    in o (created by Context.Consumer)
    in t
    in t
    in t (created by t)
    in t

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
(anonymous) @ react-dom.development.js:19527
react-dom.development.js:13413 Uncaught (in promise) Error: Objects are not valid as a React child (found: Error: Request failed with status code 500). If you meant to render a collection of children, use an array instead.
    in div (created by Er)
    in div (created by Er)
    in Er (created by uT)
    in uT (created by o)
    in div (created by o)
    in div (created by o)
    in div (created by o)
    in o (created by Context.Consumer)
    in t
    in t
    in t (created by t)
    in t
    at ku (react-dom.development.js:13413)
    at react-dom.development.js:14313
    at zd (react-dom.development.js:16762)
    at react-dom.development.js:17302
    at sp (react-dom.development.js:18627)
    at HTMLUnknownElement.g (react-dom.development.js:188)
    at Object.f (react-dom.development.js:237)
    at _ (react-dom.development.js:292)
    at im (react-dom.development.js:23203)
    at Bh (react-dom.development.js:22157)

**Comment by pedro-alves-ferreira** [comment]
Aha! Now I understand the problem. The login page is not user friendly 
at all and, above all, is quite counter intuitive:

Firstly, you need to enter the email address and the password and only 
then click register. It will tell you that a new user has been 
registered and then you just need to click login to, well, login.

We are redesigning the GUI for v2 so we don't think too much about 
fixing it but we definitely need to enhance this even before v2 and most 
definitely there has to be a validation step to avoid crashing if there 
is not data on the user and password fields. It has been like this 
forever, so I guess we just overlook it.

I am so sorry about this and please accept my apologies for not 
understanding the problem immediately. I have just added a high priority 
bug to our backlog to take care of this asap.

Pedro

**Comment by tagYourPregnant** [comment]
I should have known better. I just appreciate you getting back to me.

Do you have any sample pcaps I can use to analyze? The few that I have don't seem to want to get analyzed. I just want to make sure it is something in my end.

**Comment by pedro-alves-ferreira** [comment]
Hello,

I'm sorry for the late response.

Go to https://list.ebu.io and log in as user demo pass demo. I have uploaded a few examples, which you can download.

Regards
________________________________
De: tagYourPregnant <notifications@github.com>
Enviado: 15 de janeiro de 2021 23:01
Para: ebu/pi-list <pi-list@noreply.github.com>
Cc: Pedro Ferreira <pedro@bisect.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [ebu/pi-list] Login / Register not working as expected (#113)


I should have known better. I just appreciate you getting back to me.

Do you have any sample pcaps I can use to analyze? The few that I have don't seem to want to get analyzed. I just want to make sure it is something in my end.

**Comment by pedro-alves-ferreira** [comment]
Closed in release 1.17
