### ISSUE TITLE
Compile in Docker

### ISSUE THREAD

**Issue by pkeroulas** [ebu/pi-list#15]
Hi,
I'd like to have the libs, the binaries and everything built inside the Docker container to prevent my host from being polluted. Do we agree that it makes sense to use the same container for compile and runtime?
It would also be more convenient for dev if there is no more need to re-deploy and re-create a Docker image each time. I can try to refactor while keeping the possibility to avoid Docker. What do you think?

**Comment by promgamer** [comment]
Hi @pkeroulas,

I think that's an wonderful idea. In fact it should have been done that way already. The only reason is time constrains, just that.

Some ideas that I'd like to share:
- We **had previously some bugs from building the project in the host machine**, because of libraries (if I recall correctly, openSSL in our case) that were installed in the host system, but not available via conan. This addition would make catching bugs like this much easier and faster (**fail fast and early**).
- We should **keep separate the "building" environment from the "running" environment**. We need GCC (or clang, for instance) to build the libs and binaries, but we don't need GCC installed to run them. That's an example. I think it is a good practice to keep both environments separate.
- Right now, **everything is being copied to the docker image** in a "ready to run" state (aka, already compiled), **except for the listwebserver**, which I've tried to compile to an executable using both [pkg](https://github.com/zeit/pkg) and [nexe](https://github.com/nexe/nexe), but I had some problems (which unfortunately I don't remember :disappointed: )
- All these changes will enable us to make the next step in our CI system very easy: after each CI iteration, we would be able to have a **docker image as an artifact of that build** (and tag it along the Github's tag, which, by the way, we are not doing it right now and it is a MUST).
    - Adding another point to the discussion (because of the last point): we could adopt a "live at HEAD" strategy instead of tagging each release. In my point of view, that would require an extreme amount of work to have enough tests that gave us confidence that each push to master would give us a version that is well-tested and working as intended. And it would force us to break the API a less often than we do right now. Because of all this, we should think about tagging releases on Github and document a changelog (if we ever go with the CI improvement).
- I don't think I got what you meant by "_It would also be more convenient for dev if there is no more need to re-deploy and re-create a Docker image each time_", because **docker does layer caching**, yet the last docker commands on the Dockerfile (adding the new version of libs/executables/webserver/gui) is always need, in order to guarantee that the docker image will contain the latest version.

**Comment by pkeroulas** [comment]
Ok I understand. I'm working on a POC:
- create dev env in a  docker image based on enhanced setup scripts (avoid redundancies between script and Dockerfile)
- start the container from this image and mount the project dir as a volume (r/w from both inside and outside of the container)
- execute the build script within the container
- access the build artefacts from outside for deploy

In this way, we have a controlled build env.
