### ISSUE TITLE
rabbitmq dependency could not be satisfied

### ISSUE THREAD

**Issue by dewiweb** [ebu/pi-list#29]
Due to the recent (yesterday) merging, it seems that listwebserver now need rabbitmq docker install to work.
Maybe rabbitmq has to be external of the "pi-list" container stack or not?
Without it the listwebserver  docker container crashed due to an "econn refused" error to rabbitmq
Do you plan to integrate a rabbitmq docker container to future release?

**Comment by pedro-alves-ferreira** [comment]
Hello,

Thanks for reporting this problem.

Rabbitmq will be external to LIST's own container but will be launched using the same docker-compose file.
I'll remove the requirement for rabbitmq immediately and afterwards I'll update everything else.

Regards,

Pedro Ferreira

No dia 14/02/2019, às 13:18, dewiweb <notifications@github.com<mailto:notifications@github.com>> escreveu:


Due to the recent (yesterday) merging, it seems that listwebserver now need rabbitmq docker install to work.
Maybe rabbitmq has to be external of the "pi-list" container stack or not?
Without it the listwebserver docker container crashed due to an "econn refused" error to rabbitmq
Do you plan to integrate a rabbitmq docker container to future release?
