### ISSUE TITLE
Enable LiveMode

### ISSUE THREAD

**Issue by dewiweb** [ebu/pi-list#30]
Did you already experiment live mode and when do you plan to enable it ?

**Comment by dewiweb** [comment]
Just a little UP. I'm looking for realtime analysis capability of pi-list. After enabling live mode with --live option in docker, I'm able to launch capture via gui but there's a problem with network config of the container. Apparently it doesn't capture packets from hst network... Do you have a workaround?

**Comment by pedro-alves-ferreira** [comment]
No, we don't. We are running LIST directly on the metal when doing captures. We were told it should be possible to run from within a container but we never really tried.
If you manage to do that, please let us know.

**Comment by dewiweb** [comment]
I don't understand well the mechanism used to do realtime analysis. How can I suscribe to a live flow?Is there an autodiscovery mechanism to populate live streams list?

**Comment by pedro-alves-ferreira** [comment]
Not yet. Please bear in mind that this is still under development. Right now, we support capturing using tcpdump a stream that is statically joined to in the switch.

We are finishing automatic subscription using the 'subscribe_to' application. subscribe_to is called by the backend to listen to the stream which destination address you write in the GUI.
So the workflow will be:
- you fill the destination address field in the gui and press the button;
- the backend will launch subscribe_to with the multicast group address and the port number to listen to;
- the backend will then launch tcpdump to capture all the traffic;
- when the capture period ends, the backend stops tcpdump and start the analysis process.

**Comment by dewiweb** [comment]
Hello,
It seems that pi-list is pretty ready to enable live analysis.
Can you confirm it?
If so, what's the simple way to test live capabilities?(docker image, git clone and build.....)
Apparently, instructions for building aren't really updated.
regards,

**Comment by pedro-alves-ferreira** [comment]
Hello

It is ready for capture and analysis, not live analysis.

The easiest way to use it is to:
- run LIST as a docker container, enabling live mode;
- clone the repo;
- go to capture_probe;
- npm install
- edit to config.yml file and:
  - change the RabbitMQ URL so that it points to the IP address of the container running RabbitMQ;
  - set it to tcpdump mode;
- run: node server.js <path to config.yml>

Then you can use the GUI to add sources and perform captures.

Please let me know if it works for you or if you have any troubles. We will update the documentation soon, so your feedback is appreciated.

Regards,

Pedro
