### ISSUE TITLE
VRX calculator

### ISSUE THREAD

**Issue by ClairePap** [ebu/pi-list#38]
current_n_ calculation causes underflow detection : if my new frame comes before its theoric value, current_n calculation gives on old value and drained result is wrong. Why can't we just set current_n = old_n +1, and keep the old calcul (static_cast<double>(packet_time) / static_cast<double>(tframe)) just for initialization.

![image](https://user-images.githubusercontent.com/38779468/54907853-d5ec7980-4ee6-11e9-93e6-23ceedf98639.png)

Is it necessary to erase vrx_prev_ value on each frame start and why ?

**Comment by pedro-alves-ferreira** [comment]
Hello,

That is something we've been discussing theoretically but we haven't yet found a case where it happened. Can you please provide us with a small pcap file where that effect is apparent?

Thanks!

Pedro


No dia 25/03/2019, às 09:15, ClairePap <notifications@github.com<mailto:notifications@github.com>> escreveu:


current_n_ calculation causes underflow detection : if my new frame comes before its theoric value, current_n calculation gives on old value and drained result is wrong. Why can't we just set current_n = old_n +1, and keep the old calcul (static_cast(packet_time) / static_cast(tframe)) just for initialization.

[image]<https://user-images.githubusercontent.com/38779468/54907853-d5ec7980-4ee6-11e9-93e6-23ceedf98639.png>

Is it necessary to erase vrx_prev_ value on each frame start and why ?

**Comment by ClairePap** [comment]
Hello,

I think you can see the issue in this small pcap, but that's difficult to say without logs
[mini.zip](https://github.com/ebu/pi-list/files/3037912/mini.zip)

Claire

**Comment by pedro-alves-ferreira** [comment]
I will try it. Thanks!

De: ClairePap <notifications@github.com>
Enviada: 03 April 2019 10:37
Para: ebu/pi-list <pi-list@noreply.github.com>
Cc: Pedro Ferreira <pedro@bisect.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [ebu/pi-list] VRX calculator (#38)


Hello,

I think you can see the issue in this small pcap, but that's difficult to say without logs
mini.zip<https://github.com/ebu/pi-list/files/3037912/mini.zip>

Claire

**Comment by pedro-alves-ferreira** [comment]
Hi,

There are some independent issues here:

1) Clock synchronization

It looks like this pcap contains the output of an SDI-to-IP encapsulator, which is connected to an SDI source that is ***not*** locked to the same clock as PTP. There is at least on device on the market that locks to the SDI clock and not to PTP. If that is the case, all VRX measurements will be pointless. The device will never be able to honor the read schedule.
This is apparent in the image below, where you see that the arrival time of the first packet is drifting from PTP.
![image](https://user-images.githubusercontent.com/20090304/55563474-f0e09a00-56ed-11e9-8cb5-d9fb58eeffdc.png)
An alternative explanation is that the capture device is not locked to PTP.

2) Calculation of N

The calculation of N is based on the packet arrival time versus N x Tframe and ***not*** N x Tframe + TRoffset. If the first packet arrives in the interval `[N x Tframe, (N + 1) x Tframe[`, it will be tagged as frame N.
By definition, a packet of frame N cannot arrive before N x Tframe, because before that, frame N didn't even exist. Therefore, I don't understand your drawing in the first message on this thread. I was wrongly assuming that you meant that the problem was caused by resetting Vrx at each frame and not the calculation of N.

3) Resetting of Vrx on each frame

Other people have raised this issue before (not only but e.g. https://github.com/ebu/pi-list/issues/18). We still don't see how this can actually affect the calculation, given the algorithm we use. Note that, for each packet that is received, we calculate how many packets should have been read by a device that honors the read schedule since the beginning of the frame.
If you do have a case that proves that the algorithm is wrong, we are certainly most interested in looking at it.

Best regards,

Pedro

**Comment by ClairePap** [comment]
Ok, thanks for your explanation. My capture device wasn't connected to the PTP. Synchronized PTP totally give sense to the calculation of N, and to the reset of Vrx on each frame (without synchronization, some packets in "Vrx bucket" would be drained too early with the reset)

**Comment by pedro-alves-ferreira** [comment]
I'm glad it is clear. Thanks for confirming it.
