### ISSUE TITLE
Unable to run Docker Desktop

### ISSUE THREAD

**Issue by mikeov1** [ebu/pi-list#47]
Followed the instructions "A short guide to install ...  containerized application"
I downloaded the windows installer, and it runs and asks for permission to install, but then nothing happens.  I do not see anything installed.  So I cannot start the desktop if it is not there....

**Comment by mikeov1** [comment]
I see now that Desktop requires Win 10.  I have Win 7.  Trying Docker Toolbox

**Comment by pedro-alves-ferreira** [comment]
Hello,

Did you manage to get it working?

Regards,

Pedro
________________________________
De: mikeov1 <notifications@github.com>
Enviado: 19 de julho de 2019 20:10
Para: ebu/pi-list <pi-list@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [ebu/pi-list] Unable to run Docker Desktop (#47)


I see now that Desktop requires Win 10. I have Win 7. Trying Docker Toolbox

**Comment by mikeov1** [comment]
Pedro,
Not on that machine.  Mike W has it running on his MAC, but he needed to do
some extra work on the config file loading

Do you  think it is reasonable to get it working on a win 7 machine with
Docker Toolkit?  Or is that too hard?

Mike

**Comment by pedro-alves-ferreira** [comment]
Mike,

We've never tried Docker Toolbox ourselves. We run Docker on Linux, MacOS or Windows 10, so I have no experience with it.
If you want to try it out and run into any issues, let us know to see what we can do.

Pedro

On Jul 22 2019, at 3:45 pm, mikeov1 <notifications@github.com> wrote:
Pedro,
Not on that machine. Mike W has it running on his MAC, but he needed to do
some extra work on the config file loading

Do you think it is reasonable to get it working on a win 7 machine with
Docker Toolkit? Or is that too hard?

Mike

**Comment by tageli** [comment]
Hi Pedro,
just tried to install it myself on my computer, the issue is to get the EBU app to be install
while running 
PS C:\Docker> docker-compose up
you receive the following output 

WARNING: The EBU_LIST_WEB_APP_DOMAIN variable is not set. Defaulting to a blank string.
WARNING: The EBU_LIST_LIVE_MODE variable is not set. Defaulting to a blank string.
ERROR: build path C:\Docker\server either does not exist, is not accessible, or is not a valid URL.
I copied the yml file from here : https://github.com/ebu/pi-list/blob/master/scripts/deploy/artifacts/docker-compose.yml 

I need it to send the Json files to the EBU before the JT-NM tests
please your advise :-)
Best
Eli

**Comment by pedro-alves-ferreira** [comment]
Hi Eli,

The link was not correct in the documentation. We already updated it. I'm sorry for the inconvenience.
You should use this file: https://raw.githubusercontent.com/ebu/pi-list/master/docs/docker-compose.yml
Please let me know if it works.

Best,

Pedro

On Aug 1 2019, at 3:37 pm, tageli <notifications@github.com> wrote:
Hi Pedro,
just tried to install it myself on my computer, the issue is to get the EBU app to be install
while running
PS C:\Docker> docker-compose up
you receive the following output

WARNING: The EBU_LIST_WEB_APP_DOMAIN variable is not set. Defaulting to a blank string.
WARNING: The EBU_LIST_LIVE_MODE variable is not set. Defaulting to a blank string.
ERROR: build path C:\Docker\server either does not exist, is not accessible, or is not a valid URL.
I copied the yml file from here : https://github.com/ebu/pi-list/blob/master/scripts/deploy/artifacts/docker-compose.yml

I need it to send the Json files to the EBU before the JT-NM tests
please your advise :-)
Best
Eli

**Comment by tageli** [comment]
Hi Pedro, thank you for the update
I used the latest document on the shared folder,
Thanks
Eli

**Comment by mikeov1** [comment]
Pedro,
I never got it running in a docker.

I did some testing using the web version.    Worked well for a while then
stopped finishing the analysis.   It gets stuck as you can see in the
capture.  I can click on the unfinished entry and the results come up.
 I have been deleting files to avoid stressing the AWS behind this...   Did
I break something??
Mike

**Comment by pedro-alves-ferreira** [comment]
Hi Mike,

"I never got it running in a docker."

But did you manage to have Docker installed and running on your machine?

"It gets stuck as you can see in the capture."

Did you mean to attach a screen capture?

"Did I break something??"

I don't think so :-)

Pedro

**Comment by mikeov1** [comment]
Pedro,
I did attach a png of the screen.

pasted into message this time
[image: image.png]

Today the tool will not load - as if it is trying to analyse the files and
is stuck.   I tried to log out in the lower left corner, now cannot log in.

Can you please delete my account and I will try again?

Thanks,

Mike

**Comment by pedro-alves-ferreira** [comment]
Hi Mike,

The server ran out of space and that's why it was not responding. It's strange that it worked for me when I checked it.
Please try it again now and let me know if it is working properly.

Thanks,

Pedro

**Comment by rafaelllourenco** [comment]
Hello, Pedro. 

I'm having problems to install the EBU LIST as a docker container. I'm using W10 and Docker Desktop is running correctly

I followed "a shot guide to install..." and I got this error when run the command EBU_LIST_WEB_APP_DOMAIN=http://localhost:80 docker-compose up

![image](https://user-images.githubusercontent.com/63660923/79248585-62e7d500-7e52-11ea-867b-40d4a0ecbfc6.png)

As you can see, I create the file .yml from here https://raw.githubusercontent.com/ebu/pi-list/master/docs/docker-compose.yml and executing the commands in the respective folder.

Do you know what's going on?

Tranks,
Rafael Lourenço

**Comment by pedro-alves-ferreira** [comment]
Olá Rafael,

I'm afraid the instructions there only apply for Unix-like shells.
On Windows, you cannot use that syntax to set an environment variable when you start a process.

The easiest way to do that is to run two separate commands:

On the cmd shell, this should work:

> set EBU_LIST_WEB_APP_DOMAIN=http://localhost:80
> docker-compose up

I see that you are using PowerShell so, according to https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7#changing-environment-variables, the syntax is:

> $env:EBU_LIST_WEB_APP_DOMAIN = "http://localhost:80"
> docker-compose up

But I don't have a Windows box around to test it.

I hope this helps.

Best regards,

Pedro Ferreira
