### ISSUE TITLE
Latest release does not work

### ISSUE THREAD

**Issue by bojanul** [ebu/pi-list#68]
Hi,
I'm trying to run the Docker version but all I get is EBU logo for a second or so and than a blank screen. Older release on my other PC is running OK. Both are fresh install of Ubuntu 18.04LTS (same result with 16.0LTS)

**Comment by kalstong** [comment]
Hi bojanul,
I belieave that we have a issue regarding the default configuration of the docker network. Could you please, do `EBU_LIST_WEB_APP_DOMAIN="http://localhost:80" docker-compose up` instead `docker-compose up`. If this is the case, I'll fix that.

**Comment by bojanul** [comment]
It woks now. Thank you.

**Comment by RaymondAdeas** [comment]
Hi,
I'm having problems getting V1.6 and V1.5 to work.
The last version that is working is V1.4.

When I try to access the EBU LIST webpage I get the following errors in the console of the browser:
`Uncaught TypeError: Cannot read property 'gui' of undefined
    at App.js:141
    at ov (react-dom.development.js:16260)
    at react-dom.development.js:18794
    at Ky (react-dom.development.js:20162)
    at HTMLUnknownElement.m (react-dom.development.js:336)
    at Object.v (react-dom.development.js:385)
    at S (react-dom.development.js:440)
    at Dw (react-dom.development.js:25780)
    at sw (react-dom.development.js:24698)
    at ow (react-dom.development.js:24671)`

`The above error occurred in one of your React components:
    in Unknown
    in Unknown (created by component)
    in component (created by Context.Consumer)
    in t
    in t
    in t (created by t)
    in t`

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Unknown (created by component)
    in component (created by Context.Consumer)
    in t
    in t
    in t (created by t)
    in t`

I can get to the login page by adding '/login' in the url but when I click login I get this error:
`Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at Login.js:57`

I'm using windows 10 PCs with Google Chrome.

Any idea what the issue is?

Thanks,
Raymond

**Comment by pedro-alves-ferreira** [comment]
Hi Raymond,

I assume you are using Docker to run LIST.

I can think of 2 things that could have gone wrong:

1) Your docker-compose.yml file is not up to date

Run:

> curl -O https://raw.githubusercontent.com/ebu/pi-list/master/docs/docker-compose.yml

on the folder where you want the docker-compose.yml file.

Or refer to https://github.com/ebu/pi-list/blob/master/docs/how-to-install-on-local-docker.md

2) There is corrupted data on the database

If you don't have any valuable data in a docker volume, please run:

> docker system prune --volumes

If you need to preserve data, then find the LIST volumes:

> docker volume ls

And then delete them with:

> docker volume rm <volume names starting with list->

Then, try to run LIST again.



Please note that the latest versions default to http://localhost and no longer to port 8080.

Let me know if this solves the problem. If not, send me the logs of the docker container.

Regards,

Pedro


No dia 18/12/2019, às 13:44, RaymondAdeas <notifications@github.com><mailto:notifications@github.com> escreveu:

﻿

Hi,
I'm having problems getting V1.6 and V1.5 to work.
The last version that is working is V1.4.

When I try to access the EBU LIST webpage I get the following errors in the console of the browser:
Uncaught TypeError: Cannot read property 'gui' of undefined at App.js:141 at ov (react-dom.development.js:16260) at react-dom.development.js:18794 at Ky (react-dom.development.js:20162) at HTMLUnknownElement.m (react-dom.development.js:336) at Object.v (react-dom.development.js:385) at S (reacted om.development.js:440) at Dw (react-dom.development.js:25780) at sw (react-dom.development.js:24698) at ow (react-dom.development.js:24671)

The above error occurred in one of your React components: in Unknown in Unknown (created by component) in component (created by Context.Consumer) in t in t in t (created by t) in t

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function. in Unknown (created by component) in component (created by Context.Consumer) in t in t in t (created by t) in t

I can get to the login page by adding '/login' in the url but when I click login I get this error:
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined at Login.js:57

I'm using windows 10 PCs with Google Chrome.

Any idea what the issue is?

Thanks,
Raymond

**Comment by RaymondAdeas** [comment]
Hi Pedro,

Yes, I'm running it with docker.
I've done some tests and I think it's being caused by the port that I want to use.
If I try a port value that is not 80, it does not work.
This is the docker-compose file that I'm using:
> version: "3"
> services:
>   influxdb:
>     image: influxdb:1.4.2
>     volumes:
>       - influxdb:/var/lib/influxdb
> 
>   mongo:
>     image: mongo:4.1.10
>     volumes:
>       - mongo:/data/db
> 
>   rabbitmq:
>     image: pedroalvesferreira/rabbitmq-with-web-mqtt
>     ports:
>       - "5672:5672"
>       - "15672:15672"
>       - "15675:15675"
> 
>   list_server:
>     image: ebutech/pi-list # using the latest version
>     ports:
>       - "8080:8080"
>       - "8081"
>       - "3030"
>     environment:
>         #- EBU_LIST_WEB_APP_DOMAIN=${EBU_LIST_WEB_APP_DOMAIN}
>         - EBU_LIST_WEB_APP_DOMAIN=http://ws45:8080
>         - EBU_LIST_LIVE_MODE=${EBU_LIST_LIVE_MODE}
>     links:
>       - influxdb
>       - mongo
>       - rabbitmq
>     volumes:
>       - ${EBU_LIST_HOST_DATA_FOLDER:-listserver}:/home/
> 
> volumes:
>   mongo:
>   listserver:
>   influxdb:

In our setup we're not able to use port 80 because it's in use by another application (and I don't know how to change that in that application).

**Comment by kalstong** [comment]
Hi Raymond,

Please comment the following line on your docker-compose.yml:
*#- EBU_LIST_WEB_APP_DOMAIN=**http://ws45:8080*

And uncomment the next one:
*EBU_LIST_WEB_APP_DOMAIN=${EBU_LIST_WEB_APP_DOMAIN}*

To change the port there is 2 things that need to be modified.

One is in the port that the docker exposes.
This is done in the docker-compose.yml.
In you case is 8080. (- "*8080*:8080")

The other is to expose a Environment Variable.
There is at least 2 ways to do that.
Exposing globally to the system:
In a terminal please run the following lines:
*export EBU_LIST_WEB_APP_DOMAIN="**http://ws45:8080**"*
*docker-compose up*

Exposing in context of shell command:
In a terminal please run the following line:
*EBU_LIST_WEB_APP_DOMAIN=**"http://ws45:8080**" docker-compose up*

Please, let me know if it works

**Comment by kalstong** [comment]
Raymond,

I believe that you docker-compose.yml is not up to date.
Please follow the @pedro-alves-ferreira answer.
Let me know what happen with the newest docker-compose.yml.

In order to change port, please refer to: 
[https://github.com/ebu/pi-list/blob/master/docs/local_docker.md#choose-a-different-port](https://github.com/ebu/pi-list/blob/master/docs/local_docker.md#choose-a-different-port)

To change from 80 to 8080:
In the docker-compose.yml replace the line:
      - "80:80"
by
      - "8080:80"

and
        - EBU_LIST_WEB_APP_DOMAIN=${EBU_LIST_WEB_APP_DOMAIN}
by
        - EBU_LIST_WEB_APP_DOMAIN=http://ws45:8080


Let me know if it works

**Comment by RaymondAdeas** [comment]
Hi Kalstong,

This change made it work:
> In the docker-compose.yml replace the line:
> - "80:80"
> by
> - "8080:80"

Thanks!

I'm not really familiar with docker so I misinterpreted what the ":80" at the end meant.
I guess V1.4 was the last version that was using container port 8080?

**Comment by kalstong** [comment]
No problem at all.
Yes, V1.4 was the last version that was using container port 8080.

Now we are using a reverse proxy to have all the traffic in the same port and to avoid trouble with firewalls we modified the default container port to be 80.
