### ISSUE TITLE
Delta 1st Packet vs RTP check issue for low frame rates

### ISSUE THREAD

**Issue by RaymondAdeas** [ebu/pi-list#70]
Hi,
I've been running some tests with low frame rate video streams (30, 29.97, 25, 24, *23.98 (not supported by EBU LIST)).
The streams are being flagged as "Not Compliant" due to the "Delta 1st Packet vs RTP" measurement exceeding the pass range (min: 0, max: 1ms).
The default TROffset already exceeds the 1ms, so am I right in assuming that this is a false negative?

Thanks,
Raymond

**Comment by pedro-alves-ferreira** [comment]
Hi Andreas,

Yes, you're right. Thanks for reporting this.
We need to review that requirement. We will check with JT-NM and adjust it.

Is it possible for you to share with us a 23.98 stream? I need to see what is happening.

Thanks,

Pedro

**Comment by RaymondAdeas** [comment]
Hi Pedro,

First time someone called me Andreas :)
I've attached a pcap of a 1080p23.98 stream.

[st2110_1080p23.976.pcap.gz](https://github.com/ebu/pi-list/files/3943740/st2110_1080p23.976.pcap.gz)

Cheers,
Raymond

**Comment by pedro-alves-ferreira** [comment]
Hi Raymond,

😁 I'm sorry. That's what happens when you multi-task too much and you happened to have just talked with someone with a similar name and you're writing to someone who works for a company with a similar name.

Thanks. I'll look at the file later today.

Cheers,

Pedro

No dia 10/12/2019, às 08:37, RaymondAdeas <notifications@github.com> escreveu:

﻿

Hi Pedro,

First time someone called me Andreas :)
I've attached a pcap of a 1080p23.98 stream.

st2110_1080p23.976.pcap.gz<https://github.com/ebu/pi-list/files/3943740/st2110_1080p23.976.pcap.gz>

Cheers,
Raymond

**Comment by pedro-alves-ferreira** [comment]
Hi Raymond,

I have already added support for 23.98Hz. It will be merged into master in the next few days and I'll then close this issue.

I have also reported the issue with the validation of streams based on "Delta 1st Packet vs RTP". We will update LIST based on the outcome of the discussion within the JT-NM Tested team.

Thanks again for bringing this up.

Cheers,

Pedro

**Comment by RaymondAdeas** [comment]
Thanks Pedro.
Looking forward for the new release :)

Cheers,
Raymond

**Comment by pedro-alves-ferreira** [comment]
Hi Raymond,

A new version (1.6) is now available. Can you please check if 23.98 streams are handled correctly?

Thanks,

Pedro

**Comment by RaymondAdeas** [comment]
Hi Pedro,

I can confirm that 23.98 is handled correctly in V1.6.
Thanks!

I'll need to look into why the timestamp from my capture has such a huge offset, but that's an issue on my side.

**Comment by pedro-alves-ferreira** [comment]
Excellent! Thanks for letting me know.
