### ISSUE TITLE
Feature Request: Multicast MAC Address Validation

### ISSUE THREAD

**Issue by daniel-pebble** [ebu/pi-list#87]
We recently had an issue receiving a flow but it turned out that the sender had the wrong destination MAC address for the specified IPv4 address, it would be really nice if LIST could test for this.

**Comment by pedro-alves-ferreira** [comment]
Hello,

Thanks for pointing that out. The latest version already has that functionality in place. Please check it out and let us know if it works correctly for you.

Regards,

Pedro Ferreira

No dia 12/06/2020, às 14:29, daniel-pebble <notifications@github.com> escreveu:

﻿

We recently had an issue receiving a flow but it turned out that the sender had the wrong destination MAC address for the specified IPv4 address, it would be really nice if LIST could test for this.

**Comment by daniel-pebble** [comment]
Hi @pedro-alves-ferreira , i can confirm this feature works.  
Many thanks!

**Comment by pedro-alves-ferreira** [comment]
Excellent. Thanks!
